server:
  port: 8094
  tomcat:
    remote_ip_header: x-forwarded-for
    protocol_header: x-forwarded-proto

spring:
  application:
    name: HSPC Patient Picker

logging:
  level:
    org.springframework.security: INFO
